### ISSUE TITLE
[coffeescript] Bad regex, Invalid range end

### ISSUE THREAD

**Issue by mis2** [scopatz/nanorc#107]
Since commit https://github.com/scopatz/nanorc/pull/106/commits/a983d29c60ddfb49fea9d5940a59a606a08cdfe7 I get the following error with nano 2.6.1

```
Error in /usr/share/nano-syntax-highlighting/coffeescript.nanorc on line 4: Bad regex "[!&|=/*+\-<>]|\<(and|or|is|isnt|not)\>": Invalid range end

Press Enter to continue starting nano.
```

**Comment by scopatz** [comment]
Pull requests welcome

**Comment by mis2** [comment]
Unfortunately I don't know how to fix the regex properly, so I opened this.

**Comment by scopatz** [comment]
Maybe someone else will though :)

**Comment by meeDamian** [comment]
Here ya go :).

**Comment by scopatz** [comment]
thanks!
