### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by elofu17** [scopatz/nanorc#125]
Hi!

Please run:
cd ~/.nano/
grep ,green *

You will see that in 47 (out of 83) files, you highlight trailing whitespace as inverted green, like this:

  color ,green "[[:space:]]+$"

This is great!
Could you please add the same to all files?

**Comment by scopatz** [comment]
Please feel free to open a PR

**Comment by elofu17** [comment]
Swift response. :-)
I have never done a PR. :-/ *blush*
Is it easy?


Also, in puppet.nanorc I found an error:

color red "[[:space:]]+$"

The trailing whitespace is not shown (in red) since you forgot to invert the color.

PS: In my opinion this should be green, not red, since the extra whitespace isn't critical to puppet.

**Comment by scopatz** [comment]
Hi @elofu17 - git hub tries to make it pretty easy.  If you google around you'll find lots of documentation.

**Comment by elofu17** [comment]
That was easy. :)
Thanks!

I'll take a look at the other files on the train home.

**Comment by scopatz** [comment]
Cool, sounds good.
