### ISSUE TITLE
Color "normal" not understood

### ISSUE THREAD

**Issue by mhf-ir** [scopatz/nanorc#198]
```
Error in /home/user/.nano/etc-hosts.nanorc on line 11: Color "normal" not understood
```

```
## Make /etc/hosts nicer to read, see `man hosts 5` to see the format
syntax "/etc/hosts" "hosts"

# IPv4
color yellow "^[0-9\.]+\s"

# IPv6
icolor green "^[0-9a-f:]+\s"

# interpunction
color normal "[.:]"

# comments
color brightblack "^#.*"
```

```
nano -V
 GNU nano, version 2.9.3
 (C) 1999-2011, 2013-2018 Free Software Foundation, Inc.
 (C) 2014-2018 the contributors to nano
 Email: nano@nano-editor.org	Web: https://nano-editor.org/
 Compiled options: --disable-libmagic --disable-wrapping-as-root --enable-utf8
```

**Comment by storytime** [comment]
+1

**Comment by scopatz** [comment]
This is likely because your nano is on an older version.

**Comment by mhf-ir** [comment]
> This is likely because your nano is on an older version.

That's right but seems be your repository need 2.x and 3.x branches for coverage both versions.
Most of distros use 2.x as default editor

**Comment by scopatz** [comment]
I thought normal was added in 2.9

**Comment by mhf-ir** [comment]
> I thought normal was added in 2.9

Seems be not added. you are see ubuntu 18.04 lts error.

**Comment by tomkyle** [comment]
My solution is to install [Linuxbrew](https://linuxbrew.sh/) and brew the “nano” formula which gives me version 3.2:

```bash
$ sudo apt install linuxbrew-wrapper
# ...brewing...
# after all, one initial call is needed:
$ brew --help
$ brew install nano
```
The linuxbrew's _bin/_ dir must of course be in _$PATH_. Check which and version:
```bash
$ which nano
/home/linuxbrew/.linuxbrew/bin/nano

$ nano --version
GNU nano, Version 3.2
(C) 1999-2011, 2 ...
```

**Comment by KsenZ** [comment]
Same error with Nano 2.7.4, default on Debian 9.9

**Comment by scopatz** [comment]
PRs welcom!

**Comment by DesertPunk** [comment]
i've submitted a pull request that will fix the issue on all installs by changing the "normal" to "white"

**Comment by scopatz** [comment]
As explained in some other issues, white is not a good substitue for normal.  It is better to have copies of the file with version numbers that support older nanos.

**Comment by okainov** [comment]
Same issue here, normal nano from Ubuntu 18, 2.5.3

**Comment by esler** [comment]
My suggestion is to create a new branch for legacy support. We can define minimal compatible version of `nano` (eg. 2.3.x from RHEL 7). Then we can fix all incompatibilities there, without changing the master. After that user can decide which branch will checkout based on its version.

**Comment by scopatz** [comment]
@esler that is also a good idea!

**Comment by esler** [comment]
@scopatz let's do that. I've changed PR #224 to work with branch/version `v2.9`. Please create that branch and I can change the target in the PR. thx

**Comment by scopatz** [comment]
Created!

**Comment by esler** [comment]
Ok, I've changed base of my PR and fixed installation guide. You can merge it :-)

**Comment by evilSwanson** [comment]
> Ok, I've changed base of my PR and fixed installation guide. You can merge it :-)

What happened to this PR?

**Comment by scopatz** [comment]
People should use the `v2.9` branch if they have old versions of nano. This can probably be closed
