### ISSUE TITLE
.j2 syntax no highlighting

### ISSUE THREAD

**Issue by thuban-arrakis** [scopatz/nanorc#205]
Hey, thanx for your work. 
I have a little issue with weird nanorc behaviour with .j2 files in Nano 2.7.4
First of all, i have both `include` options in `/etc/nanorc` 
`# cat /etc/nanorc | grep html`
`include "~/.nano/html.nanorc"`
`include "~/.nano/html.j2.nanorc"`
And such as language.nanorc 
`# ll /root/.nano/ | grep html`
`-rw-r--r-- 1 root root 1756 Jan 20 14:34 html.j2.nanorc`
`-rw-r--r-- 1 root root 1756 Jan 20 14:44 html.nanorc`
But with that all is fine in others languages. 
![image](https://user-images.githubusercontent.com/41233597/51439980-6386cf80-1cd2-11e9-8f98-7d66070455d7.png)
![image](https://user-images.githubusercontent.com/41233597/51440139-c37e7580-1cd4-11e9-847b-9cca6e274429.png)
![image](https://user-images.githubusercontent.com/41233597/51440236-09880900-1cd6-11e9-8079-d26016d668cb.png)

**Comment by scopatz** [comment]
Pull requests welcome!

**Comment by BarbzYHOOL** [comment]
would be interesting, true

**Comment by thuban-arrakis** [comment]
sorry. not relevant already
