### ISSUE TITLE
Please provide a link to the original nano repo in README

### ISSUE THREAD

**Issue by E3V3A** [scopatz/nanorc#207]
Many issues are talking about the upstream (orginial?) nano repo. But there are no links anywhere. 
Please add a link to the "upstream" nano repo.

**Comment by scopatz** [comment]
I am not sure what you are talking about specifically. There is no upstream nanorc repo.  There is the nano project itself

**Comment by E3V3A** [comment]
Yep, that's what I meant. :)

**Comment by scopatz** [comment]
Ahh. OK.  PRs welcome :)

**Comment by E3V3A** [comment]
Sure: 
1. click on [README](https://github.com/scopatz/nanorc/blob/master/Readme.rst)
2. Then click on the edit button and
3. Add: 
  - `[avrdude site](http://savannah.nongnu.org/projects/avrdude)`
  - `[avrdude repo](http://svn.savannah.gnu.org/viewvc/avrdude/)`

and *voila'*  No PR needed!

**Comment by scopatz** [comment]
Yep I am totally willing to merge a PR to that effect

**Comment by lopho** [comment]
@E3V3A what repo is that? Definitely _not_ nano.
This is nano:
Project page: https://www.nano-editor.org/
Git repo: https://git.savannah.gnu.org/cgit/nano.git

**Comment by E3V3A** [comment]
@lopho 
Whoops! Copy paste errrorrrr LoL!
