### ISSUE TITLE
Add release versions

### ISSUE THREAD

**Issue by krathalan** [scopatz/nanorc#255]
The AUR `nano-syntax-highlighting-git` package is a fairly popular package with 119 upvotes (https://aur.archlinux.org/packages/nano-syntax-highlighting-git). Foxboron (an Arch trusted user and part of their security team) created a thread on Reddit asking for repository packaging requests. I requested this package, but the request was denied because upstream (here) doesn't provided releases, only the master branch: 

> `-git` packages are probably never going to hit repositories. Needs a release.  

https://www.reddit.com/r/archlinux/comments/dhf377/package_request_thread/f3o3i0p/?context=3

Would you consider making official releases?

**Comment by SuperSandro2000** [comment]
Tag at every commit?

**Comment by krathalan** [comment]
@SuperSandro2000 I'm not sure what you mean. I assume you mean that "master is the release," and I understand that, but perhaps a commit could be declared as a version every month or so for the purposes of official packaging?

**Comment by SuperSandro2000** [comment]
Yeah, master is release. Probably a good idea then would be to tag it YEAR.MONTH cause semantic does not make sense here I think.

**Comment by scopatz** [comment]
Done! Thanks for pushing on this.

**Comment by Foxboron** [comment]
https://www.archlinux.org/packages/community/any/nano-syntax-highlighting/

**Comment by scopatz** [comment]
Thanks!
