### ISSUE TITLE
Undefined Versioning Scheme

### ISSUE THREAD

**Issue by wsdmatty** [scopatz/nanorc#257]
I recently picked up maintaining this project in the Archlinux User Repository and I have one request. 

I am a stickler for versioning numbers in the packages I maintain, and although I see you have a separate branch with a version number, there are no annotated tags between version 0.0.0 and HEAD, and on the master branch, the only tag (un-annotated) is a datemark, not a version number.

Would it be possible to have you tag some commits to make versioning a thing for clarity? Or explain the difference between master and v2.9 and why versioning would be superfluous?

It looks like the best common ancestor of master and v2.9 is commit 7ae493a1e39fa4301782c27d11d968f7a1cce927
If that commit were tagged.. say 2.0, it would at least give the versioning somewhere to start. 

Currently the version number of this project in the AUR is 474.421a5c4-1 .. which is basically just "how many commits in the repo?" It'd be awesome if we could get an actual version number. To satisfy my OCD.

Thanks for taking the time to read this.

**Comment by wsdmatty** [comment]
After poking around I've found that the difference between master and v2.9 is exactly that.. the name. And two slight differences in etc-hosts.nanorc and html.nanorc which could likely be merged. That could be done, and the revision tagged 2.9.1, and my OCD is happy. >_>

**Comment by scopatz** [comment]
The 2.9 branch is for nano v2.9 (which is super old) and I do not recommend using it on modern systems.  Sadly some people still want to use these archaic versions of nano. Master is for recent versions of nano.  I will only be releasing tags against the master, so there is no reason to worry about the 2.9 branch.  The version scheme is just the data in YYYY.MM.DD format.

**Comment by wsdmatty** [comment]
Ookay. Fair enough.
I guess i was thrown off by the initial commit being v0.0.0 and then a 2.9 branch.
