### ISSUE TITLE
Rnw.nanorc Bad regex

### ISSUE THREAD

**Issue by BarbzYHOOL** [scopatz/nanorc#267]
When I open anything with nano, I get this error before it opens

```
Error in /usr/share/nano/better-syntax-highlighting/Rnw.nanorc on line 19: Bad regex "([a-zA-Z0-9_\-$\.]*)\(": Invalid range end
```

Here is the commit I am on:
c705a50 2019-12-02 Anthony Scopatz (HEAD -> master, origin/master, origin/HEAD) Merge pull request #265 from msfjarvis/systemd

**Comment by scopatz** [comment]
maybe try using the v2.9 branch?

**Comment by BarbzYHOOL** [comment]
i quickly checked out v2.9 and it doesn't display any error

can you fix it in master too ? xD

**Comment by BarbzYHOOL** [comment]
so should I use v2.9 or master or what? @scopatz

**Comment by SuperSandro2000** [comment]
Yes, you should use V2.9 as it is for V2.9 or older. The master branch is for newer Nano versions.

**Comment by BarbzYHOOL** [comment]
omg i just realized it corresponds with my nano version which is .... v2.9 

Such a coincidence because I had to build nano from scratch to get it to v2.9 loool, thank you guys, i didn't realize

**Comment by olserra** [comment]
Still happens for me this error, even with the new code on master. Anyone? I m using a mac...

**Comment by mcnesium** [comment]
I see this on Debian Buster with nano v3.2

**Comment by davidhcefx** [comment]
Still happens for me with nano v7.2
