### ISSUE TITLE
MacOs - Running nano as sudo is not using syntax highlighting

### ISSUE THREAD

**Issue by jacobkaufman** [scopatz/nanorc#321]
When I run `nano` as `sudo nano` it just runs the default nano setup, but when I run the command as my username then it works fine. I've looked all over for another `.nanorc` file that it might be pulling from and cant find any other then the one in `/etc` which I have already added the highlighting to. I'm wondering if this is maybe because `sudo` overwriting my environment variables but I'm still new to all of that. Any guidance would be great. Thank you!

**Comment by scopatz** [comment]
You probably need to have `/root/.nanorc`

**Comment by jacobkaufman** [comment]
I tried to create a root folder but on MacOS the root directory is read-only. I finally figured it out. For some reason running sudo disables all user config so to enable it I have to run `sudo nano --rcfile=/etc/nanorc $file_name` and it works! I think I'm  just gonna make and alias for this and call it a day. Thank you for your help and your work!
