### ISSUE TITLE
[python] No syntax highlighting for built-in function bool()

### ISSUE THREAD

**Issue by czechuuu** [scopatz/nanorc#327]
`bool()` is a built-in function that converts to boolean type and neither the function nor its dunder sister `__bool__` are getting highlighted.
![image](https://user-images.githubusercontent.com/55449302/91334437-40d26c00-e7cf-11ea-9d9f-beccd45bc058.png)

**Comment by scopatz** [comment]
Thanks! PRs welcome!

**Comment by czechuuu** [comment]
Just created a [pull request](https://github.com/scopatz/nanorc/pull/328) to solve this issue
