### ISSUE TITLE
Bad regex in php.nanorc, sh.nanorc & zsh.nanorc using nano 2.3.6 on Mac OS X from brew

### ISSUE THREAD

**Issue by ChristopherA** [scopatz/nanorc#41]
Using GNU nano version 2.3.6 (on the Mac after `brew tap homebrew/dupes` & `brew install nano`), copying the recommended starting .nanorc from the clone, I get the following errors:
```
Error in /Users/ChristopherA/.nano/php.nanorc on line 30: Bad regex "('[^']*?')|(\"[^\"]*?\")": repetition-operator operand invalid

Error in /Users/ChristopherA/.nano/sh.nanorc on line 11: Bad regex "^\s+?[0-9A-Z_]+\s+?\(\)": repetition-operator operand invalid

Error in /Users/ChristopherA/.nano/zsh.nanorc on line 2: Bad regex "\.?zsh[^\.]+?$": repetition-operator operand invalid

Error in /Users/ChristopherA/.nano/zsh.nanorc on line 23: Bad regex "^\s+?(function\s+)?[0-9A-Z_]+\s+?\(\)": repetition-operator operand invalid
```
For now I have copied copied php.nanorc and sh.nanorc from brew files at /usr/local/share/nano/, but I've found no replacement for the bad zsh.nanoc.

-- Christopher Allen

**Comment by ddarbyson** [comment]
@AjarKeen you're right. https://github.com/justinribeiro/nanorc/commit/449447fffeba6fd472c2472027bb96ca9141313b fixes the issue

**Comment by scopatz** [comment]
I'd happily accept a PR!

**Comment by michaellopez** [comment]
@scopatz Please review #51
