### ISSUE TITLE
'(' in javascript is there.. but set to black.

### ISSUE THREAD

**Issue by whardier** [scopatz/nanorc#46]
Using this repository.. just open up a new javascript file and type ()... the ( is set to the background color.

I can't figure this out however.. I don't see where that is obvious in the javascript.nanorc.

**Comment by ZhaoMiing** [comment]
ah...still not fixed

**Comment by MatthewCox** [comment]
It looks like it's there to reset the color after the previous line highlights it brightblue.
https://github.com/scopatz/nanorc/blob/master/javascript.nanorc#L6

Obviously that doesn't work as intended if you're using a dark terminal background.

I'd suggest changing it to `color brightblue "[()]"` and just highlight both parens everywhere instead.
