### ISSUE TITLE
Extending ledger syntax to include beancount

### ISSUE THREAD

**Issue by simon-v** [scopatz/nanorc#54]
Beancount is a ledger-like accounting system that has a very ledger-like syntax. As such, beancount files can be partially parsed with the ledger syntax highlighting rules, provided that the file is named "*.ledger". The following modification to the "ledger.nanorc" file extends the syntax highlighting to beancount files (at least in a basic way).

```
1c1
< syntax "ledger" "(^|\.|/)ledger$"
---
> syntax "ledger" "(^|\.|/)ledger|lgr|beancount$"
3,4c3,4
< color brightmagenta  "^([0-9]{4}/[0-9]{2}/[0-9]{2}|[=~]) .*"
< color blue   "^[0-9]{4}/[0-9]{2}/[0-9]{2}"
---
> color brightmagenta  "^([0-9]{4}(/|-)[0-9]{2}(/|-)[0-9]{2}|[=~]) .*"
> color blue   "^[0-9]{4}(/|-)[0-9]{2}(/|-)[0-9]{2}"
```

**Comment by scopatz** [comment]
Pull requests accepted

**Comment by simon-v** [comment]
I'm thinking i'm pretty much done for now.
