### ISSUE TITLE
License for nanorc files?

### ISSUE THREAD

**Issue by agordon** [scopatz/nanorc#59]
Hello @scopatz,

Thanks for a terrific resource. Would you mind specifying the license for the files in your README (or in a separate file / in each file's comment) ? Just to help share the code in a clear way.
Hopefully, it's a permissive license (e.g. MIT/BSD/CC-SA) ?

Thanks!

**Comment by scopatz** [comment]
Hello @agordon - there already is a license file: https://github.com/scopatz/nanorc/blob/master/license

**Comment by agordon** [comment]
totally missed it!
thanks!
