### ISSUE TITLE
Need some quotes on the local .nanorc file

### ISSUE THREAD

**Issue by overthetop** [scopatz/nanorc#66]
Hey guys,
nano didn't show highlighting till I put quotes on every include statement in that file? Should I fire a pull request with the fix?

 GNU nano version 2.2.6 (compiled 16:56:37, Jul 16 2014)
 (C) 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
 2008, 2009 Free Software Foundation, Inc.
 Email: nano@nano-editor.org	Web: http://www.nano-editor.org/
 Compiled options: --disable-wrapping-as-root --enable-color --enable-extra --enable-multibuffer --enable-nanorc --enable-utf8

**Comment by scopatz** [comment]
Yeah, PRs very welcome. Thanks
