### ISSUE TITLE
Syntax definition titles conflict with nano's internals

### ISSUE THREAD

**Issue by ThomasR** [scopatz/nanorc#90]
nano comes with predefined .nanorc files, which are located in `/usr/share/nano/` (may be somewhere else on your OS)

It is a bad idea to redefine existing syntax definitions, since that can cause other syntax definitions to break. For example:
```
syntax "xml"      # ignored!
…                 # ignored!
syntax "markdown" # ignored!
…                 # ignored!
syntax "xml"
…
```
This also happens if the definitions come from different files, and even if they're included automatically. For example, including xml.nanorc may break the highlighting for markdown(!) — see #87

```
# include /usr/share/nano/*.nanorc # nano does this internally
include "~/.nano/markdown.nanorc"
include "~/.nano/xml.nanorc" # redefines "xml" syntax, and thus breaks markdown
```
Results may vary, depending on the order and amount of includes.

A quick fix consists in using different syntax names.

Here is a list of nano's bundled syntax names in v2.5.3
```plain
asm
autoconf
awk
c
changelog
cmake
css
sources.list
default
elisp
fortran
ebuild
/etc/portage
go
groff
guile
html
java
javascript
json
lua
makefile
man
mgp
mutt
nanorc
nftables
m
ocaml
patch
perl
php
po
sql
pov
python
ruby
sh
spec
tcl
tex
texinfo
xml
```

And these are problematic, since they get redefined by this project:
```plain
asm
awk
cmake
c
css
fortran
gentoo
go
groff
html
java
json
lua
makefile
man
mutt
nanorc
ocaml
patch
perl6
perl
php
po
pov
python
ruby
sh
sql
tcl
tex
```

**Comment by scopatz** [comment]
Feel free to open a PR!

**Comment by ThomasR** [comment]
I'm not happy with renaming everything, and I feel like there must be a better fix. Let me look into that.

**Comment by ThomasR** [comment]
Looks like nano 2.3 introduced [the `extendsyntax` keyword](http://www.nano-editor.org/dist/v2.3/nanorc.5.html#SYNTAX%20HIGHLIGHTING) for that exact purpose, but I guess many people are still on version 2.x, right?

**Comment by astronautlevel2** [comment]
Given that ubuntu 14.04 (The most recent LTS release) is still on nano 2.2.6, I feel it would be a bad idea to implement extendsyntax.

**Comment by ThomasR** [comment]
So we wait one more month for 16.04? :wink:
